### ISSUE TITLE
compilation issue on arch linux 8/15

### ISSUE THREAD

**Issue by sudopluto** [miracle-wm-org/miracle-wm#210]
`home/pranav/git/miracle-wm/src/renderer.cpp:252:35: error: cannot declare variable ‘outline’ to be of abstract type ‘{anonymous}::OutlineRenderable’
  252 |                 OutlineRenderable outline(*r, data.outline_context.size, data.outline_context.color.a);
         |                                   ^~~~~~~
/home/pranav/git/miracle-wm/src/renderer.cpp:58:7: note:   because the following virtual functions are pure within ‘{anonymous}::OutlineRenderable’:
  58 | class OutlineRenderable : public mir::graphics::Renderable
       |       ^~~~~~~~~~~~~~~~~
In file included from /home/pranav/git/miracle-wm/src/renderer.h:28,
                 from /home/pranav/git/miracle-wm/src/renderer.cpp:21:
/usr/local/include/mirplatform/mir/graphics/renderable.h:60:34: note:     ‘virtual mir::geometry::RectangleD mir::graphics::Renderable::src_bounds() const’
   60 |     virtual geometry::RectangleD src_bounds() const = 0;
        |                                  ^~~~~~~~~~
make[2]: *** [CMakeFiles/miracle-wm-implementation.dir/build.make:272: CMakeFiles/miracle-wm-implementation.dir/src/renderer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/miracle-wm-implementation.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

**Comment by sudopluto** [comment]
to make a bit more readable: 
![image](https://github.com/user-attachments/assets/6c6cc03d-9604-4c0f-9589-05dcffcbaf18)

**Comment by sudopluto** [comment]
build with v0.3.2 checked out, going to try older releases

**Comment by sudopluto** [comment]
edit: first going to try compiling mir to latest tagged release first

**Comment by mattkae** [comment]
Oof that's my bad! I was accidentally building against Mir's release candidate in 0.3.1 instead of  the release. I should remove that v0.3.1 tag entirely since it won't work. Please stick to 0.3.2 for now :)

**Comment by sudopluto** [comment]
sorry, been busy, will give it a go and update and close the issue if that fixes everything

edit: and either way, going to ping the maintainer of mir in the aur to help get that in shape, since at least from the aur side, don't think it makes sense trying to separate  out mir / libs + devel / demos etc.

hopefully can do that in the future, similar to fedora: https://src.fedoraproject.org/rpms/mir/blob/rawhide/f/mir.spec

**Comment by mattkae** [comment]
@sudopluto Any update on this by the way?

**Comment by sudopluto** [comment]
@mattkae  the orphaned mir aur package got adopted and opened a communication line with the new maintainer, should be move forwards now. im wrapping up exams / a project at work, should be able to make a first version in a couple of days

**Comment by sudopluto** [comment]
sorry for late update, someone adopted the mir package in arch, and someone else made a miracle-wm package. im going to try and daily drive it and report issues, for now made PRs to add the AUR package to install guides
