### ISSUE TITLE
Does release 0.8.x want an old version of Mir/Miral?

### ISSUE THREAD

**Issue by blitzgneisserin** [miracle-wm-org/miracle-wm#727]
Hi,

I just wanted to test the newest stable version but I am having several issues.

My hardware are a desktop and a laptop, the former with amd ryzen 7 + nvidia (no built in gpu), the latter intel/nvidia (newer, 16 inch, 4k screen). The OSs I tested this on are Debian (13) and Ubuntu 25.10.

1. I installed the snap on Ubuntu 25.10 - does not start, with or with or without nvidia.

2. I tried to compile Miracle on Ubuntu 25.10 - the compiler complains that it need a much older Mir/miral - building starts, but then aborts because of the error.

3. Tried to compile on Debian 13 - same result.

```
anna@anna-ms7c96:~/Downloads/miracle-wm-0.8.2$ cmake --build build
[  1%] Building CXX object miracle-wm-config/CMakeFiles/miracle-wm-config.dir/src/miracle-wm-config.cpp.o
/home/anna/Downloads/miracle-wm-0.8.2/miracle-wm-config/src/miracle-wm-config.cpp:24:10: fatal error: miral/hover_click.h: No such file or directory
   24 | #include "miral/hover_click.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [miracle-wm-config/CMakeFiles/miracle-wm-config.dir/build.make:79: miracle-wm-config/CMakeFiles/miracle-wm-config.dir/src/miracle-wm-config.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:286: miracle-wm-config/CMakeFiles/miracle-wm-config.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

```

**Comment by FabioLolix** [comment]
Hi, I add the same error some days ago; the issues was that `mir` was old v2.20.0 installed versus v2.23.0 the latest available, building from Arch Linux

**Comment by blitzgneisserin** [comment]
> Hi, I add the same error some days ago; the issues was that `mir` was old v2.20.0 installed versus v2.23.0 the latest available, building from Arch Linux

Is it possible that the dev is using mir from ubuntu 24.04?

**Comment by blitzgneisserin** [comment]
I just tried to compile on Ubuntu 24.04, doesn't work, miral is too old. It looks like this software is being developted on an oldish system with a self compiled specific version of miral, which is not in the offical Ubuntu repos.

Well I would like this to work properly because I want to write and article about Miracle for an German IT magazine. So far I can only write it about release 0.7.1.

**Comment by mattkae** [comment]
> I just tried to compile on Ubuntu 24.04, doesn't work, miral is too old. It looks like this software is being developted on an oldish system with a self compiled specific version of miral, which is not in the offical Ubuntu repos.
> 
> Well I would like this to work properly because I want to write and article about Miracle for an German IT magazine. So far I can only write it about release 0.7.1.

Hiya. It should build against latest Miral. Unfortunately for the Mir team, the latest can only be gotten from the Mir team ppa: https://launchpad.net/~mir-team/+archive/ubuntu/release

The version in the archive is old in order to not break the Lomiri project, but we are in the process of remedying that.

**Comment by blitzgneisserin** [comment]
Well 0.8.2 defintley does not build with the version of miral which is in the ubuntu 25.10 repo. I think thats pretty new.

**Comment by FabioLolix** [comment]
But which version is?

**Comment by blitzgneisserin** [comment]
I was able to build the newest release now, it definitely needs the newest mir(al) from the ppa. @FabioLolix I think in Arch it should be automatically in the AUR. Thanks @mattkae. This should be mentioned though somewhere in a prominent place in the documentation, maybe in the compiling instructions.

**Comment by FabioLolix** [comment]
>  @FabioLolix I think in Arch it should be automatically in the AUR

No, that's fruit of manual labor

**Comment by mattkae** [comment]
> I was able to build the newest release now, it definitely needs the newest mir(al) from the ppa. [@FabioLolix](https://github.com/FabioLolix) I think in Arch it should be automatically in the AUR. Thanks [@mattkae](https://github.com/mattkae). This should be mentioned though somewhere in a prominent place in the documentation, maybe in the compiling instructions.

Understood! I'll add this ticket to my list to update that. That's an artifact of working with the old Mir package on Debian, which is unfortunate. Hopefully changing soon as the Ubuntu Touch folks update to latest this year 🤞

**Comment by mattkae** [comment]
Does this make things clearer? https://wiki.miracle-wm.org/develop/getting_started/building/#from-source

**Comment by bricke** [comment]
If I follow that guide, I still get blocked here:
```
[ 63%] Linking CXX static library libmiracle-wm-implementation.a
[ 63%] Built target miracle-wm-implementation
[ 64%] Building CXX object CMakeFiles/miracle-wm.dir/src/main.cpp.o
[ 65%] Linking CXX executable miracle-wm
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libmirserver.so: undefined reference to `mir::input::MouseKeysKeymap::MouseKeysKeymap()@MIR_CORE_2.21'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libmirserver.so: undefined reference to `mir::input::MouseKeysKeymap::get_action(unsigned int) const@MIR_CORE_2.21'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libmirserver.so: undefined reference to `mir::input::MouseKeysKeymap::MouseKeysKeymap(std::initializer_list<std::pair<unsigned int, mir::input::MouseKeysKeymap::Action> >)@MIR_CORE_2.21'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/miracle-wm.dir/build.make:104: miracle-wm] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:187: CMakeFiles/miracle-wm.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
matt@macmini:~/workspace/miracle-wm$ 
```

I have tried both the `v0.8.2` and the latest from `develop`, same error from both

**Comment by bricke** [comment]
@mattkae a package is missing from that list that needs to be installed: `libmirrenderer-dev`, if you develop on desktop, you will also need: `mir-graphics-drivers-desktop`

**Comment by mattkae** [comment]
> [@mattkae](https://github.com/mattkae) a package is missing from that list that needs to be installed: `libmirrenderer-dev`, if you develop on desktop, you will also need: `mir-graphics-drivers-desktop`

`mir-graphics-drivers-desktop` is necessary, I will add it!

As of 2.25, `libmirrenderer-dev` is now deprecated and has been folded into `libmirplatform-dev`

**Comment by mattkae** [comment]
https://github.com/miracle-wm-org/miracle-wm-wiki/pull/18

**Comment by bricke** [comment]
> libmirplatform-dev

As of today, if I don't have `libmirrenderer-dev` installed it doesn't compile:

```
matt@macmini:~/workspace/miracle-wm$ cmake --build build
[  3%] Built target miracle-wm-config
[  4%] Building CXX object CMakeFiles/miracle-wm-implementation.dir/src/renderer.cpp.o
In file included from /home/matt/workspace/miracle-wm/src/renderer.cpp:21:
/home/matt/workspace/miracle-wm/src/renderer.h:29:10: fatal error: mir/renderer/renderer.h: No such file or directory
   29 | #include <mir/renderer/renderer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/miracle-wm-implementation.dir/build.make:317: CMakeFiles/miracle-wm-implementation.dir/src/renderer.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/miracle-wm-implementation.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by Sunderland93** [comment]
Hello. I am also experiencing problems with building 0.8.2 with Mir 2.25.2 on Debian 13:

```
[ 58%] Building CXX object CMakeFiles/miracle-wm-implementation.dir/src/dying_surface_manager.cpp.o
/usr/bin/c++ -DCOMPILING_AGAINST_DEV=0 -I/build/miracle-wm-0.8.2/SYSTEM -I/usr/include/miral -I/usr/include/mircore -I/usr/include/mircommon -I/usr/include/mirplatform -I/usr/include/mircommon-internal -I/usr/include/mirserver-internal -I/usr/include/mirserver -I/usr/include/uuid -I/usr/include/mirwayland -I/build/miracle-wm-0.8.2/include -I/build/miracle-wm-0.8.2/miracle-wm-config/include -I/build/miracle-wm-0.8.2/miracle-wm-config/SYSTEM -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /usr/include/libevdev-1.0 -g -O2 -ffile-prefix-map=/build/miracle-wm-0.8.2=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -w -O3 -DNDEBUG -std=c++23 -O3 -march=native -pthread -Winvalid-pch -include /build/miracle-wm-0.8.2/obj-x86_64-linux-gnu/CMakeFiles/miracle-wm-implementation.dir/cmake_pch.hxx -MD -MT CMakeFiles/miracle-wm-implementation.dir/src/dying_surface_manager.cpp.o -MF CMakeFiles/miracle-wm-implementation.dir/src/dying_surface_manager.cpp.o.d -o CMakeFiles/miracle-wm-implementation.dir/src/dying_surface_manager.cpp.o -c /build/miracle-wm-0.8.2/src/dying_surface_manager.cpp
In file included from /build/miracle-wm-0.8.2/src/forwarding_surface.cpp:18:
/build/miracle-wm-0.8.2/src/forwarding_surface.h:48:10: error: 'const mir::wayland::Weak<mir::frontend::WlSurface>& miracle::ForwardingSurface::wayland_surface()' marked 'override', but does not override
   48 |     auto wayland_surface() -> const mir::wayland::Weak<mir::frontend::WlSurface>& override;
      |          ^~~~~~~~~~~~~~~
[ 60%] Building CXX object CMakeFiles/miracle-wm-implementation.dir/src/shader_2d.cpp.o
/usr/bin/c++ -DCOMPILING_AGAINST_DEV=0 -I/build/miracle-wm-0.8.2/SYSTEM -I/usr/include/miral -I/usr/include/mircore -I/usr/include/mircommon -I/usr/include/mirplatform -I/usr/include/mircommon-internal -I/usr/include/mirserver-internal -I/usr/include/mirserver -I/usr/include/uuid -I/usr/include/mirwayland -I/build/miracle-wm-0.8.2/include -I/build/miracle-wm-0.8.2/miracle-wm-config/include -I/build/miracle-wm-0.8.2/miracle-wm-config/SYSTEM -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /usr/include/libevdev-1.0 -g -O2 -ffile-prefix-map=/build/miracle-wm-0.8.2=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -w -O3 -DNDEBUG -std=c++23 -O3 -march=native -pthread -Winvalid-pch -include /build/miracle-wm-0.8.2/obj-x86_64-linux-gnu/CMakeFiles/miracle-wm-implementation.dir/cmake_pch.hxx -MD -MT CMakeFiles/miracle-wm-implementation.dir/src/shader_2d.cpp.o -MF CMakeFiles/miracle-wm-implementation.dir/src/shader_2d.cpp.o.d -o CMakeFiles/miracle-wm-implementation.dir/src/shader_2d.cpp.o -c /build/miracle-wm-0.8.2/src/shader_2d.cpp
/build/miracle-wm-0.8.2/src/forwarding_surface.cpp: In member function 'const mir::wayland::Weak<mir::frontend::WlSurface>& miracle::ForwardingSurface::wayland_surface()':
/build/miracle-wm-0.8.2/src/forwarding_surface.cpp:143:22: error: 'using std::__shared_ptr_access<mir::scene::Surface, __gnu_cxx::_S_atomic, false, false>::element_type = class mir::scene::Surface' {aka 'class mir::scene::Surface'} has no member named 'wayland_surface'
  143 |     return surface_->wayland_surface();
      |                      ^~~~~~~~~~~~~~~
[ 61%] Building CXX object CMakeFiles/miracle-wm-implementation.dir/src/wlr-output-management-unstable-v1_wrapper.cpp.o
/usr/bin/c++ -DCOMPILING_AGAINST_DEV=0 -I/build/miracle-wm-0.8.2/SYSTEM -I/usr/include/miral -I/usr/include/mircore -I/usr/include/mircommon -I/usr/include/mirplatform -I/usr/include/mircommon-internal -I/usr/include/mirserver-internal -I/usr/include/mirserver -I/usr/include/uuid -I/usr/include/mirwayland -I/build/miracle-wm-0.8.2/include -I/build/miracle-wm-0.8.2/miracle-wm-config/include -I/build/miracle-wm-0.8.2/miracle-wm-config/SYSTEM -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /usr/include/libevdev-1.0 -g -O2 -ffile-prefix-map=/build/miracle-wm-0.8.2=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -w -O3 -DNDEBUG -std=c++23 -O3 -march=native -pthread -Winvalid-pch -include /build/miracle-wm-0.8.2/obj-x86_64-linux-gnu/CMakeFiles/miracle-wm-implementation.dir/cmake_pch.hxx -MD -MT CMakeFiles/miracle-wm-implementation.dir/src/wlr-output-management-unstable-v1_wrapper.cpp.o -MF CMakeFiles/miracle-wm-implementation.dir/src/wlr-output-management-unstable-v1_wrapper.cpp.o.d -o CMakeFiles/miracle-wm-implementation.dir/src/wlr-output-management-unstable-v1_wrapper.cpp.o -c /build/miracle-wm-0.8.2/src/wlr-output-management-unstable-v1_wrapper.cpp
In file included from /build/miracle-wm-0.8.2/src/dying_surface_manager.cpp:21:
/build/miracle-wm-0.8.2/src/forwarding_surface.h:48:10: error: 'const mir::wayland::Weak<mir::frontend::WlSurface>& miracle::ForwardingSurface::wayland_surface()' marked 'override', but does not override
   48 |     auto wayland_surface() -> const mir::wayland::Weak<mir::frontend::WlSurface>& override;
      |          ^~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/miracle-wm-implementation.dir/build.make:643: CMakeFiles/miracle-wm-implementation.dir/src/forwarding_surface.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 62%] Building CXX object CMakeFiles/miracle-wm-implementation.dir/src/wlr-ouput-management-unstable-v1.cpp.o
/usr/bin/c++ -DCOMPILING_AGAINST_DEV=0 -I/build/miracle-wm-0.8.2/SYSTEM -I/usr/include/miral -I/usr/include/mircore -I/usr/include/mircommon -I/usr/include/mirplatform -I/usr/include/mircommon-internal -I/usr/include/mirserver-internal -I/usr/include/mirserver -I/usr/include/uuid -I/usr/include/mirwayland -I/build/miracle-wm-0.8.2/include -I/build/miracle-wm-0.8.2/miracle-wm-config/include -I/build/miracle-wm-0.8.2/miracle-wm-config/SYSTEM -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /usr/include/libevdev-1.0 -g -O2 -ffile-prefix-map=/build/miracle-wm-0.8.2=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -w -O3 -DNDEBUG -std=c++23 -O3 -march=native -pthread -Winvalid-pch -include /build/miracle-wm-0.8.2/obj-x86_64-linux-gnu/CMakeFiles/miracle-wm-implementation.dir/cmake_pch.hxx -MD -MT CMakeFiles/miracle-wm-implementation.dir/src/wlr-ouput-management-unstable-v1.cpp.o -MF CMakeFiles/miracle-wm-implementation.dir/src/wlr-ouput-management-unstable-v1.cpp.o.d -o CMakeFiles/miracle-wm-implementation.dir/src/wlr-ouput-management-unstable-v1.cpp.o -c /build/miracle-wm-0.8.2/src/wlr-ouput-management-unstable-v1.cpp
make[3]: *** [CMakeFiles/miracle-wm-implementation.dir/build.make:659: CMakeFiles/miracle-wm-implementation.dir/src/dying_surface_manager.cpp.o] Error 1
make[3]: Leaving directory '/build/miracle-wm-0.8.2/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:190: CMakeFiles/miracle-wm-implementation.dir/all] Error 2
make[2]: Leaving directory '/build/miracle-wm-0.8.2/obj-x86_64-linux-gnu'
make[1]: *** [Makefile:139: all] Error 2
make[1]: Leaving directory '/build/miracle-wm-0.8.2/obj-x86_64-linux-gnu'
dh_auto_build: error: cd obj-x86_64-linux-gnu && make -j12 "INSTALL=install --strip-program=true" VERBOSE=1 returned exit code 2
make: *** [debian/rules:6: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
I: copying local configuration
E: Failed autobuilding of package
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: cleaning the build env 
I: removing directory /media/DATA/pbuilder/build//514313 and its subdirectories
```

**Comment by mattkae** [comment]
I'll get a minor release for this out tomorrow, sorry about that

**Comment by mattkae** [comment]
@Sunderland93 Released if you want to try it out: https://github.com/miracle-wm-org/miracle-wm/releases/tag/v0.8.3

**Comment by markstos** [comment]
Recommend closing as outdated now that 0.9.x is released.

**Comment by mattkae** [comment]
Yes I think we can close this @markstos . Let me know if something is wrong, but v0.10 should fix everything.

**Comment by markstos** [comment]
Thanks!
